### ISSUE TITLE
Importing a /var/lib/mysql/ directory from a bare metal seems to run into issues.

### ISSUE THREAD

**Issue by Leopere** [MarvAmBass/docker-mysql#2]
root@a:/home/REDACTED# docker run -ti --name REDACTED-mysql -e 'ADMIN_USER=root' -e 'ADMIN_PASSWORD=REDACTED' -e 'BIND_ADDRESS=0.0.0.0' -p 3307:3306 -v /home/REDACTED/mysqldata:/var/lib/mysql marvambass/mysql

> > disable auto-backups (mysqldump)
> > bind mysql daemon to 0.0.0.0
> > db installed
> > starting mysql daemon
> > you can connect via mysql cli with the following command:
> >    mysql -u root -p -h 172.17.0.140
> > 150429 00:21:44 mysqld_safe Can't log to error log and syslog at the same time.  Remove all --log-error configuration options for --syslog to take effect.
> > 150429 00:21:44 mysqld_safe Logging to '/var/log/mysql/error.log'.
> > 150429 00:21:44 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
> > 150429 00:21:44 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended

Probably the version used in the docker-mysql container.
  root@5c6bf01b4293:/# mysql --version
  mysql  Ver 14.14 Distrib 5.5.43, for debian-linux-gnu (x86_64) using readline 6.3

The version of mysql from the bare metal.
root@server:/var/run# mysql --version
mysql  Ver 14.14 Distrib 5.5.41, for debian-linux-gnu (x86_64) using readline 6.2

**Comment by MarvAmBass** [comment]
first thought: some rights problem, or it destroys the db while the db gets installed. need to check it more further

**Comment by Leopere** [comment]
I've been wrestling with this for longer than I'd like so I switched to just simply trying to import this massive 8gig sql dump which is disconnecting now as well annoyingly enough.  

Since this was probably my fault I'll close this ticket.
