### ISSUE TITLE
My SQL dump is too big.  It keeps failing at about 11%

### ISSUE THREAD

**Issue by Leopere** [MarvAmBass/docker-mysql#3]
I've been feeding this SQL dump into this container using a variant of the following.

  pv mysqlbackup-2015.04.28.sql | mysql -u root -pREDACTED -h $(docker inspect --format='{{.NetworkSettings.IPAddress}}' REDACTED)
I used PV as a suggestion from a thread I found that shows a progress bar of the process.  The import seems to reach about 20 million rows before it fails.  
  http://dba.stackexchange.com/questions/58493/mysql-failing-and-very-slow-on-importing-a-large-file

Reading from this tutorial:

  https://www.digitalocean.com/community/tutorials/how-to-migrate-a-mysql-database-to-a-new-server-on-ubuntu-14-04

I exported every bit I could from the previous bare metal which apparently weighs in at about 8gigs.

From the dba.stackexchange.com question it seems that someones made a suggestion to play with configs but theres no obvious way to change other settings in this image.  Could there be some?

**Comment by MarvAmBass** [comment]
Hi Chamunks,

well as far as I know, the import should work without a problem with your approach.

It seems like some limitations of the mysql serivce or the container. Maybe you've set some limits (max container size) etc.

I'm not a mysql specialist, but you could try to import everything with my phpmyadmin container, I haven't ever had a problem this way - and you might get better debugging output

**Comment by Leopere** [comment]
Thats fair I was basically wondering if there was some magic environment vars that I couldn't see that I could use to modify the mysql cont

**Comment by Leopere** [comment]
This was a me error seems that importing via the command line just is really fragile so run it inside of a screen or tmux session and leave it alone.
