### ISSUE TITLE
Importing a Baremetal /var/lib/mysql directory runs into uid/gid issues.

### ISSUE THREAD

**Issue by Leopere** [MarvAmBass/docker-mysql#4]
This container should persist the correct ownerships into the container for any external volumes.  

Otherwise you get weird database issues that seem undocumented so what you need to do to fix it currently, if your database volume doesn't have the correct permissions is enter the container on launch so you can get the GID and UID by running this command:

```
id mysql
```

Inside of the container followed by:

```
chown -R uid:gid /var/lib/mysql/
```

The way I entered my container was similar to this.

```
docker run -ti --name app-mysql -e 'ADMIN_USER=root' -e 'ADMIN_PASSWORD=REDACTED' -e 'BIND_ADDRESS=0.0.0.0' -e 'BACKUP_ENABLED=yes' -e 'BACKUP_CRON_TIME=3 30 * * *' -p 127.0.0.1:3307:3306 -v /home/excelsion/mysqldata:/var/lib/mysql -v /path/mysqlbackup:/var/mysql-backup -v /path/mysqlconf:/etc/mysql marvambass/mysql /bin/bash
```

I don't think that it would really break much to make this happen on initialization.

**Comment by MarvAmBass** [comment]
fixed it, you can check if it works now ;)

**Comment by Leopere** [comment]
Seems to be good thanks!
